// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import { client, appControllerPing, appControllerAuthorizedPing, clerkControllerClerkWebhookSync } from '../services.gen';
import type { ClerkControllerClerkWebhookSyncError, ClerkControllerClerkWebhookSyncResponse } from '../types.gen';

type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): QueryKey<TOptions>[0] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return params;
};

export const appControllerPingQueryKey = (options?: Options) => [
    createQueryKey("appControllerPing", options)
];

export const appControllerPingOptions = (options?: Options) => { return queryOptions({
    queryFn: async ({ queryKey }) => {
        const { data } = await appControllerPing({
            ...options,
            ...queryKey[0],
            throwOnError: true
        });
        return data;
    },
    queryKey: appControllerPingQueryKey(options)
}); };

export const appControllerAuthorizedPingQueryKey = (options?: Options) => [
    createQueryKey("appControllerAuthorizedPing", options)
];

export const appControllerAuthorizedPingOptions = (options?: Options) => { return queryOptions({
    queryFn: async ({ queryKey }) => {
        const { data } = await appControllerAuthorizedPing({
            ...options,
            ...queryKey[0],
            throwOnError: true
        });
        return data;
    },
    queryKey: appControllerAuthorizedPingQueryKey(options)
}); };

export const clerkControllerClerkWebhookSyncQueryKey = (options?: Options) => [
    createQueryKey("clerkControllerClerkWebhookSync", options)
];

export const clerkControllerClerkWebhookSyncOptions = (options?: Options) => { return queryOptions({
    queryFn: async ({ queryKey }) => {
        const { data } = await clerkControllerClerkWebhookSync({
            ...options,
            ...queryKey[0],
            throwOnError: true
        });
        return data;
    },
    queryKey: clerkControllerClerkWebhookSyncQueryKey(options)
}); };

export const clerkControllerClerkWebhookSyncMutation = () => { const mutationOptions: UseMutationOptions<ClerkControllerClerkWebhookSyncResponse, ClerkControllerClerkWebhookSyncError, Options> = {
    mutationFn: async (options) => {
        const { data } = await clerkControllerClerkWebhookSync({
            ...options,
            throwOnError: true
        });
        return data;
    }
}; return mutationOptions; };