import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import { ThemeProvider } from "../providers/theme.provider";
import Providers from "./_components/layout.providers";
import SiteNavigation from "./_components/site.navigation";
import { SiteFooter } from "./_components/site.footer";

const font = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          font.variable
        )}
      >
        <Providers>
          <SiteNavigation>
            {children}
            <SiteFooter />
          </SiteNavigation>
        </Providers>
      </body>
    </html>
  );
}
