import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import SiteNavigation from "./_components/site.navigation";
import { SiteFooter } from "./_components/site.footer";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import { client } from "@/lib/api";
import ClientProvider from "@/components/providers/client-provider";

const font = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

client.setConfig({
  baseUrl: "http://localhost:3000",
});

client.interceptors.request.use(async (request, options) => {
  request.headers.set("Authorization", `Bearer ${await auth().getToken()}`);
  return request;
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          font.variable
        )}
      >
        <ClerkProvider>
          <ClientProvider>
            <SiteNavigation>
              {children}
              <SiteFooter />
            </SiteNavigation>
          </ClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
