// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type { AppControllerPingError, AppControllerPingResponse, AppControllerAuthorizedPingError, AppControllerAuthorizedPingResponse, ClerkControllerClerkWebhookSyncError, ClerkControllerClerkWebhookSyncResponse } from './types.gen';

export const appControllerPing = (options?: Options) => { return (options?.client ?? client).get<AppControllerPingResponse, AppControllerPingError>({
    ...options,
    url: '/ping'
}); };

export const appControllerAuthorizedPing = (options?: Options) => { return (options?.client ?? client).get<AppControllerAuthorizedPingResponse, AppControllerAuthorizedPingError>({
    ...options,
    url: '/ping-authorized'
}); };

export const clerkControllerClerkWebhookSync = (options?: Options) => { return (options?.client ?? client).post<ClerkControllerClerkWebhookSyncResponse, ClerkControllerClerkWebhookSyncError>({
    ...options,
    url: '/clerk/sync'
}); };