// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { AppControllerPingError, AppControllerPingResponse, AppControllerAuthorizedPingError, AppControllerAuthorizedPingResponse, ClerkControllerClerkWebhookSyncError, ClerkControllerClerkWebhookSyncResponse } from './types.gen';

export const client = createClient(createConfig());

export const appControllerPing = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<AppControllerPingResponse, AppControllerPingError, ThrowOnError>({
    ...options,
    url: '/ping'
}); };

export const appControllerAuthorizedPing = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<AppControllerAuthorizedPingResponse, AppControllerAuthorizedPingError, ThrowOnError>({
    ...options,
    url: '/ping-authorized'
}); };

export const clerkControllerClerkWebhookSync = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<ClerkControllerClerkWebhookSyncResponse, ClerkControllerClerkWebhookSyncError, ThrowOnError>({
    ...options,
    url: '/clerk/sync'
}); };