// This file is auto-generated by @hey-api/openapi-ts

export type AppControllerPingResponse = (unknown);

export type AppControllerPingError = unknown;

export type AppControllerAuthorizedPingResponse = (unknown);

export type AppControllerAuthorizedPingError = unknown;

export type ClerkControllerClerkWebhookSyncResponse = (unknown);

export type ClerkControllerClerkWebhookSyncError = unknown;