// This file is auto-generated by @hey-api/openapi-ts

export type AppControllerPingResponse = unknown;

export type AppControllerPingError = unknown;

export type AppControllerAuthorizedPingResponse = unknown;

export type AppControllerAuthorizedPingError = unknown;

export type ClerkControllerClerkWebhookSyncResponse = unknown;

export type ClerkControllerClerkWebhookSyncError = unknown;

export type $OpenApiTs = {
  "/ping": {
    get: {
      res: {
        "200": unknown;
      };
    };
  };
  "/ping-authorized": {
    get: {
      res: {
        "200": unknown;
      };
    };
  };
  "/clerk/sync": {
    post: {
      res: {
        "201": unknown;
      };
    };
  };
};
